### ISSUE TITLE
US AD-3 Gestion commerciale des produits

### ISSUE THREAD

**Issue by vince958** [DTAFormation/pizzeria-web-admin-nov-2015#13]
En tant qu'**administrateur** je veux pouvoir **gérer les ingredients, les pizzas, les desserts, les boissons, les menus** de la pizzeria.

Critères d'acceptation:
- [x] Lister les produits (Pizza, Boisson, Dessert)
- [x] Afficher le détail d'un produit
- [x] Ajouter un produit
- [x] Modifier un produit
- [x] Supprimer un produit
- [x] Lister les ingredients
- [x] Ajouter un ingredient
- [x] Supprimer un ingredient
- Gestion des menus (Non prit en charge dans le spint 1 et 2)

**Comment by montreuild** [comment]
Reste le problème des ingredients
