### ISSUE TITLE
US CU-2 Validation des commandes prêtes

### ISSUE THREAD

**Issue by vince958** [DTAFormation/pizzeria-web-admin-nov-2015#8]
En tant que **cuisinier**, je veux pouvoir **valider les commandes prêtes en cuisine** afin de les envoyer en distribution.

Critères d'acceptation:
- [x] Lorsque **je sélectionne la commande prête ou tous les éléments séparément**, alors le **bouton de validation de préparation se déverrouille**
- [x] Lorsque **je valide une commande en cuisine**, alors elle disparaît de l'écran de préparation et est dispatchée selon son type vers la caisse ou la livraison

**Comment by MHayet** [comment]
gg
